-- ==============================================================================
-- VALEN MAKEUP - ESQUEMA DE BASE DE DATOS SUPABASE (CLOUD POSTGRESQL)
-- ==============================================================================
-- Copia y pega todo este script en el "SQL Editor" de tu proyecto en https://supabase.com
-- y haz clic en el botón "RUN" para crear las tablas y permisos necesarios.
-- ==============================================================================

-- 1. Tabla de Productos
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    image TEXT NOT NULL DEFAULT 'img/product_1.jpg',
    page INTEGER DEFAULT 1,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    category TEXT NOT NULL DEFAULT 'Maquillaje',
    category_id INTEGER DEFAULT 2,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Categorías
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Habilitar Seguridad por Filas (Row Level Security)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 4. Políticas de Acceso Público y Administración (Permite Lectura, Inserción, Edición y Eliminación)
DROP POLICY IF EXISTS "Public Read Products" ON public.products;
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Insert Products" ON public.products;
CREATE POLICY "Public Insert Products" ON public.products FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Update Products" ON public.products;
CREATE POLICY "Public Update Products" ON public.products FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Delete Products" ON public.products;
CREATE POLICY "Public Delete Products" ON public.products FOR DELETE USING (true);

DROP POLICY IF EXISTS "Public All Categories" ON public.categories;
CREATE POLICY "Public All Categories" ON public.categories FOR ALL USING (true);

-- 5. Insertar Categorías Principales
INSERT INTO public.categories (id, name) VALUES
    (1, 'Cuidado Facial y Corporal'),
    (2, 'Maquillaje'),
    (3, 'Cabello y Ducha'),
    (4, 'Accesorios'),
    (5, 'Bloomshell')
ON CONFLICT (name) DO NOTHING;

-- 6. Habilitar Sincronización en Tiempo Real (Realtime)
-- Permite que si eliminas o agregas un producto, se actualice en tiempo real
-- en todos los celulares y computadores de los clientes sin recargar la página.
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
    EXCEPTION
        WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.categories;
    EXCEPTION
        WHEN duplicate_object THEN NULL;
    END;
END $$;
